# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8sPodsViewer < Formula
  desc "Terminal UI for watching live pod CPU and memory usage in Kubernetes"
  homepage "https://github.com/lavluda/k8s-pods-viewer"
  version "1.5.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/lavluda/k8s-pods-viewer/releases/download/v1.5.0/k8s-pods-viewer_Darwin_all.tar.gz"
    sha256 "952203bc54e07bc35b67fcb34ed2bd1d4379a9b815ad61af4dd5fdbfe0e7b700"

    define_method(:install) do
      bin.install "k8s-pods-viewer"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lavluda/k8s-pods-viewer/releases/download/v1.5.0/k8s-pods-viewer_Linux_x86_64.tar.gz"
      sha256 "7f5568f87ad5dd439f523cd8f85fb334a75ad608d36ed3e81e00a5346f7a3166"
      define_method(:install) do
        bin.install "k8s-pods-viewer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lavluda/k8s-pods-viewer/releases/download/v1.5.0/k8s-pods-viewer_Linux_arm64.tar.gz"
      sha256 "1776662af814cffc7f01327caa2f3ddefaf0a4120d7e0d5f4b8a0dea79bd22c6"
      define_method(:install) do
        bin.install "k8s-pods-viewer"
      end
    end
  end

  test do
    system bin/"k8s-pods-viewer", "-version"
  end
end
